services:
  preview:
    image: nginx:1-alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/entrypoint.sh:/entrypoint.sh:ro
      - ./dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NGINX_SYSLOG_SERVER=${NGINX_SYSLOG_SERVER:-}
      - NGINX_SET_REAL_IP_FROM=${NGINX_SET_REAL_IP_FROM:-}
    entrypoint: ["/entrypoint.sh"]
